server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: product_route
          uri: http://product-service-url:8080  # ?? product ???? URL
          predicates:
            - Path=/product/**